<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <MetalamaEnabled>false</MetalamaEnabled>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Metalama.Testing.UnitTesting" Version="2026.1.28" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Talby.Core.ResxAccess\Talby.Core.ResxAccess.csproj" />
  </ItemGroup>
</Project>
