<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <MetalamaRemoveCompileTimeOnlyCode>false</MetalamaRemoveCompileTimeOnlyCode>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Talby.Core.ResxAccess.Tests" />
    <InternalsVisibleTo Include="Talby.Core.ResxAccess.AspectTests" />
    <PackageReference Include="Metalama.Framework" Version="2026.1.28" />
    <None Include="buildTransitive/Talby.Core.ResxAccess.targets" Pack="true" PackagePath="buildTransitive/" />
  </ItemGroup>

</Project>
