// Error TRESX001 on `InvalidIdentifier`: `Invalid Reference Resource: 'Labels.resx' Resource Key 'Bad' has a malformed Formatting Placeholder: Invalid Named Placeholder identifier 'bad-name'.`
// Error TRESX001 on `UnsupportedType`: `Invalid Reference Resource: 'Labels.resx' Resource Key 'Bad' has a malformed Formatting Placeholder: Unsupported Argument Type 'float' for Named Placeholder 'name'.`
// Error TRESX001 on `UnsupportedTypeSpelling`: `Invalid Reference Resource: 'Labels.resx' Resource Key 'Bad' has a malformed Formatting Placeholder: Unsupported Argument Type 'System.Int32' for Named Placeholder 'name'.`
// Error TRESX001 on `MalformedNullableType`: `Invalid Reference Resource: 'Labels.resx' Resource Key 'Bad' has a malformed Formatting Placeholder: Unsupported Argument Type 'int??' for Named Placeholder 'name'.`
// Error TRESX001 on `ConflictingTypes`: `Invalid Reference Resource: 'Labels.resx' Resource Key 'Bad' has a malformed Formatting Placeholder: Conflicting Argument Types 'int' and 'long' for Named Placeholder 'name'.`
// Error TRESX001 on `ConflictingNullability`: `Invalid Reference Resource: 'Labels.resx' Resource Key 'Bad' has a malformed Formatting Placeholder: Conflicting Argument Types 'string' and 'string?' for Named Placeholder 'name'.`
// Error TRESX001 on `IndexedNameCollision`: `Invalid Reference Resource: 'Labels.resx' Resource Key 'Bad' has a malformed Formatting Placeholder: Named Placeholder 'arg2' collides with generated parameter 'arg2'.`
// Error TRESX001 on `ResourceCultureCollision`: `Invalid Reference Resource: 'Labels.resx' Resource Key 'Bad' has a malformed Formatting Placeholder: Named Placeholder 'resourceCulture' collides with generated parameter 'resourceCulture'.`
// Error TRESX001 on `FormattingCultureCollision`: `Invalid Reference Resource: 'Labels.resx' Resource Key 'Bad' has a malformed Formatting Placeholder: Named Placeholder 'formattingCulture' collides with generated parameter 'formattingCulture'.`
// Error TRESX001 on `MalformedAlignment`: `Invalid Reference Resource: 'Labels.resx' Resource Key 'Bad' has a malformed Formatting Placeholder: Input string was not in a correct format. Failure to parse near offset 3. Expected an ASCII digit.`
// Error TRESX001 on `MalformedFormat`: `Invalid Reference Resource: 'Labels.resx' Resource Key 'Bad' has a malformed Formatting Placeholder: Nested opening brace.`
// Error TRESX004 on `ChangedType`: `Invalid Localized Resource: 'Labels.es.resx' Resource Key 'Summary' has a malformed Formatting Placeholder: Named Placeholder 'name' declares Argument Type 'long'; the Reference Resource requires 'int'.`
// Error TRESX004 on `ChangedReferenceNullability`: `Invalid Localized Resource: 'Labels.es.resx' Resource Key 'Summary' has a malformed Formatting Placeholder: Named Placeholder 'name' declares Argument Type 'string'; the Reference Resource requires 'string?'.`
// Error TRESX004 on `ChangedValueNullability`: `Invalid Localized Resource: 'Labels.es.resx' Resource Key 'Summary' has a malformed Formatting Placeholder: Named Placeholder 'name' declares Argument Type 'int'; the Reference Resource requires 'int?'.`
// Error TRESX004 on `ChangedUntypedArgument`: `Invalid Localized Resource: 'Labels.es.resx' Resource Key 'Summary' has a malformed Formatting Placeholder: Named Placeholder 'name' declares Argument Type 'string'; the Reference Resource requires 'object?'.`
// Error TRESX004 on `MissingNullableIdentity`: `Invalid Localized Resource: 'Labels.es.resx' Resource Key 'Summary' must use exactly the Reference Resource's Placeholder Contract (arguments: name).`
// Error TRESX004 on `AdditionalIndexedIdentity`: `Invalid Localized Resource: 'Labels.es.resx' Resource Key 'omitted-key' must use exactly the Reference Resource's Placeholder Contract (arguments: name, 0, 2).`
// Error TRESX004 on `MissingNamedIdentity`: `Invalid Localized Resource: 'Labels.es.resx' Resource Key 'Summary' must use exactly the Reference Resource's Placeholder Contract (arguments: name, 0, 2).`
// Error TRESX004 on `AdditionalNamedIdentity`: `Invalid Localized Resource: 'Labels.es.resx' Resource Key 'Summary' must use exactly the Reference Resource's Placeholder Contract (arguments: name).`
// Error TRESX004 on `MalformedNamedTranslation`: `Invalid Localized Resource: 'Labels.es.resx' Resource Key 'Summary' has a malformed Formatting Placeholder: Unclosed Formatting Placeholder.`